apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: cert-issuer-pb
 namespace: passbolt
spec:
 acme:
   email: steven.schramm91@googlemail.com
   # We use the staging server here for testing to avoid hitting
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: passbolt-key
   solvers:
     - dns01:
         cloudflare:
           apiTokenSecretRef:
             name: cloudflare-api-token-secret
             key: api-token
